<a href="https://colab.research.google.com/github/UAPH451551/PH451_551_Sp25/blob/main/Resources/Saving_Files_To_Drive.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Saving Files

In this notebook we'll be looking at how to save files to google drive. <br>
Note: you may want to create a new google account to do this if you <br>
don't want to risk accidentally modifying your personal google drive.

## Step 1: Mounting google drive to colab

Click on the folder icon on the far left of the screen and then click <br>
the "Mount Drive" icon which looks like a folder with the google drive <br>
triangle symbol on it. This will add the following two lines of code to <br>
your notebook. Running these will ask permission for access to your <br>
google account and will then connect your google drive to colab.

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## Step 2: Saving and loading files in drive using some common formats

Note: The standard file path for your google drive is this: <br>
`/content/drive/MyDrive/`

You can further save to specific folders in your drive by adding to the <br>
filepath.

In [7]:
import numpy as np
import pandas as pd
from torch import nn
import torch

In [8]:
array = np.array((1,2,3))
np.save('/content/drive/MyDrive/array.npy', array)
print(array)
array2 = np.load('/content/drive/MyDrive/array.npy')
print(array2)

[1 2 3]
[1 2 3]


In [9]:
dataframe = pd.DataFrame((1,2,3))
dataframe.to_csv('/content/drive/MyDrive/dataframe.csv')
print(dataframe)
dataframe2 = pd.read_csv('/content/drive/MyDrive/dataframe.csv')
print(dataframe2)
# Note that writing to and reading from csv may modify the headers unless your
# original dataframe has headers included.

   0
0  1
1  2
2  3
   Unnamed: 0  0
0           0  1
1           1  2
2           2  3


In [14]:
model = nn.Sequential()
model.append(nn.Linear(3, 64))
model.append(nn.ReLU())
model.append(nn.Linear(64, 8))

# Save the entire model
torch.save(model, 'model.h5')
# Load the entire model
model2 = torch.load('model.h5')

# Save just the model weights
torch.save(model.state_dict(), "model_weights.h5")

# Build a new model
model3 = nn.Sequential()
model3.append(nn.Linear(3, 64))
model3.append(nn.ReLU())
model3.append(nn.Linear(64, 8))

# Load weights for model from h5 file
model3.load_state_dict(torch.load('model_weights.h5'))

print(model)
print(model2)
print(model3) # This will have a different return since it's

Sequential(
  (0): Linear(in_features=3, out_features=64, bias=True)
  (1): ReLU()
  (2): Linear(in_features=64, out_features=8, bias=True)
)
Sequential(
  (0): Linear(in_features=3, out_features=64, bias=True)
  (1): ReLU()
  (2): Linear(in_features=64, out_features=8, bias=True)
)
Sequential(
  (0): Linear(in_features=3, out_features=64, bias=True)
  (1): ReLU()
  (2): Linear(in_features=64, out_features=8, bias=True)
)


## Step 3: Saving general python files using pickle

Pickle is a compression and storage protocol for python. It can be used <br>
for general python objects. Note: it is easy to overwrite your files <br>
using pickle so you should be especially careful with 'wb' (write) vs <br> 'rb' (read).

In [15]:
import pickle as pkl
import numpy as np

In [16]:
array = np.array((1,2,3))
pkl.dump(array, open('array.p', 'wb'))
print(array)
array2 = pkl.load(open('array.p', 'rb'))
print(array2)

[1 2 3]
[1 2 3]
